import type { ClaimWithDetails } from "@shared/schema";

export async function generateClaimPDF(claim: ClaimWithDetails): Promise<Buffer> {
  // Simple text-based PDF generation for now
  // In production, you'd use a proper PDF library like puppeteer or jsPDF
  
  const content = `
MOTOR ACCIDENT INSURANCE CLAIM REPORT
=====================================

Claim ID: ${claim.id}
Policy Number: ${claim.policyNumber}
Status: ${claim.status.toUpperCase()}
Date Created: ${new Date(claim.createdAt).toLocaleDateString()}
${claim.submittedAt ? `Date Submitted: ${new Date(claim.submittedAt).toLocaleDateString()}` : ''}

CLAIMANT INFORMATION
-------------------
Name: ${claim.claimant.firstName} ${claim.claimant.lastName}
Email: ${claim.claimant.email}

POLICY DETAILS
--------------
Branch: ${claim.branchName || 'N/A'}
Agent: ${claim.agentName || 'N/A'}
Last Payment: ${claim.lastPaymentDate ? new Date(claim.lastPaymentDate).toLocaleDateString() : 'N/A'}
Insured Type: ${claim.insuredType}

ACCIDENT DETAILS
---------------
Date: ${claim.accidentDate ? new Date(claim.accidentDate).toLocaleDateString() : 'N/A'}
Time: ${claim.accidentTime || 'N/A'}
Location: ${claim.accidentLocation || 'N/A'}
Description: ${claim.accidentDescription || 'N/A'}

VEHICLE INFORMATION
------------------
${claim.vehicle ? `
Make: ${claim.vehicle.make}
Model: ${claim.vehicle.model}
Year: ${claim.vehicle.year || 'N/A'}
Registration: ${claim.vehicle.registrationNumber}
Color: ${claim.vehicle.color || 'N/A'}
` : 'No vehicle information available'}

DAMAGE ASSESSMENT
-----------------
Vehicle Damage: ${claim.vehicleDamageDescription || 'N/A'}
Goods Damaged: ${claim.goodsDamaged ? 'Yes' : 'No'}
${claim.goodsDamaged ? `Goods Description: ${claim.goodsDescription || 'N/A'}` : ''}

PHOTOS UPLOADED
--------------
${claim.damagedPhotos?.length ? 
  claim.damagedPhotos.map(photo => 
    `- ${photo.angle} (${photo.isGoodsPhoto ? 'Goods' : 'Vehicle'}) - ${photo.detectedDamages?.length || 0} damages detected`
  ).join('\n') 
  : 'No photos uploaded'}

AI ANALYSIS SUMMARY
------------------
${claim.damagedPhotos?.length ? 
  `Total Photos: ${claim.damagedPhotos.length}
Total Detected Damages: ${claim.damagedPhotos.reduce((sum, photo) => sum + (photo.detectedDamages?.length || 0), 0)}
` : 'No AI analysis available'}

${claim.individualDetails ? `
INDIVIDUAL DETAILS
-----------------
Full Name: ${claim.individualDetails.firstName} ${claim.individualDetails.middleName || ''} ${claim.individualDetails.surname}
ID Number: ${claim.individualDetails.idNumber}
Nationality: ${claim.individualDetails.nationality || 'N/A'}
Date of Birth: ${claim.individualDetails.dateOfBirth ? new Date(claim.individualDetails.dateOfBirth).toLocaleDateString() : 'N/A'}
Mobile: ${claim.individualDetails.mobile || 'N/A'}
Email: ${claim.individualDetails.email || 'N/A'}
Address: ${claim.individualDetails.physicalAddress || 'N/A'}
` : ''}

${claim.corporateDetails ? `
CORPORATE DETAILS
----------------
Registered Name: ${claim.corporateDetails.registeredName}
Registration Number: ${claim.corporateDetails.registrationNumber}
Country: ${claim.corporateDetails.countryOfRegistration || 'N/A'}
Business: ${claim.corporateDetails.tradeBusiness || 'N/A'}
Years in Operation: ${claim.corporateDetails.yearsInOperation || 'N/A'}
` : ''}

${claim.driver ? `
DRIVER INFORMATION
-----------------
Name: ${claim.driver.fullName}
License Number: ${claim.driver.licenseNumber}
License Class: ${claim.driver.licenseClass || 'N/A'}
Issue Date: ${claim.driver.issueDate ? new Date(claim.driver.issueDate).toLocaleDateString() : 'N/A'}
Expiry Date: ${claim.driver.expiryDate ? new Date(claim.driver.expiryDate).toLocaleDateString() : 'N/A'}
` : ''}

${claim.bankDetails ? `
BANK DETAILS
-----------
Bank Name: ${claim.bankDetails.bankName}
Account Name: ${claim.bankDetails.accountName}
Account Number: ${claim.bankDetails.accountNumber}
Branch: ${claim.bankDetails.branchName || 'N/A'}
Swift Code: ${claim.bankDetails.swiftCode || 'N/A'}
` : ''}

Report Generated: ${new Date().toLocaleString()}
Generated by: ClaimFlow AI Staff Portal
  `.trim();

  // Convert text to PDF buffer (simplified)
  return Buffer.from(content, 'utf8');
}