import type { ClaimWithDetails } from "@shared/schema";
import puppeteer from 'puppeteer';

export async function generateClaimPDF(claim: ClaimWithDetails): Promise<Buffer> {
  const browser = await puppeteer.launch({
    args: ['--no-sandbox', '--disable-setuid-sandbox']
  });
  
  const page = await browser.newPage();
  
  // Generate comprehensive HTML content
  const htmlContent = `
MOTOR ACCIDENT INSURANCE CLAIM REPORT
=====================================

Claim ID: ${claim.id}
Policy Number: ${claim.policyNumber}
Status: ${claim.status.toUpperCase()}
Date Created: ${new Date(claim.createdAt).toLocaleDateString()}
${claim.submittedAt ? `Date Submitted: ${new Date(claim.submittedAt).toLocaleDateString()}` : ''}

CLAIMANT INFORMATION
-------------------
Name: ${claim.claimant.firstName} ${claim.claimant.lastName}
Email: ${claim.claimant.email}

POLICY DETAILS
--------------
Branch: ${claim.branchName || 'N/A'}
Agent: ${claim.agentName || 'N/A'}
Last Payment: ${claim.lastPaymentDate ? new Date(claim.lastPaymentDate).toLocaleDateString() : 'N/A'}
Insured Type: ${claim.insuredType}

ACCIDENT DETAILS
---------------
Date: ${claim.accidentDate ? new Date(claim.accidentDate).toLocaleDateString() : 'N/A'}
Time: ${claim.accidentTime || 'N/A'}
Location: ${claim.accidentLocation || 'N/A'}
Description: ${claim.accidentDescription || 'N/A'}

VEHICLE INFORMATION
------------------
${claim.vehicle ? `
Make: ${claim.vehicle.make}
Model: ${claim.vehicle.model}
Year: ${claim.vehicle.year || 'N/A'}
Registration: ${claim.vehicle.registrationNumber}
Color: ${claim.vehicle.color || 'N/A'}
` : 'No vehicle information available'}

DAMAGE ASSESSMENT
-----------------
Vehicle Damage: ${claim.vehicleDamageDescription || 'N/A'}
Goods Damaged: ${claim.goodsDamaged ? 'Yes' : 'No'}
${claim.goodsDamaged ? `Goods Description: ${claim.goodsDescription || 'N/A'}` : ''}

PHOTOS UPLOADED
--------------
${claim.damagedPhotos?.length ? 
  claim.damagedPhotos.map(photo => 
    `- ${photo.angle} (${photo.isGoodsPhoto ? 'Goods' : 'Vehicle'}) - ${photo.detectedDamages?.length || 0} damages detected`
  ).join('\n') 
  : 'No photos uploaded'}

AI ANALYSIS SUMMARY
------------------
${claim.damagedPhotos?.length ? 
  `Total Photos: ${claim.damagedPhotos.length}
Total Detected Damages: ${claim.damagedPhotos.reduce((sum, photo) => sum + (photo.detectedDamages?.length || 0), 0)}
` : 'No AI analysis available'}

${claim.individualDetails ? `
INDIVIDUAL DETAILS
-----------------
Full Name: ${claim.individualDetails.firstName} ${claim.individualDetails.middleName || ''} ${claim.individualDetails.surname}
ID Number: ${claim.individualDetails.idNumber}
Nationality: ${claim.individualDetails.nationality || 'N/A'}
Date of Birth: ${claim.individualDetails.dateOfBirth ? new Date(claim.individualDetails.dateOfBirth).toLocaleDateString() : 'N/A'}
Mobile: ${claim.individualDetails.mobile || 'N/A'}
Email: ${claim.individualDetails.email || 'N/A'}
Address: ${claim.individualDetails.physicalAddress || 'N/A'}
` : ''}

${claim.corporateDetails ? `
CORPORATE DETAILS
----------------
Registered Name: ${claim.corporateDetails.registeredName}
Registration Number: ${claim.corporateDetails.registrationNumber}
Country: ${claim.corporateDetails.countryOfRegistration || 'N/A'}
Business: ${claim.corporateDetails.tradeBusiness || 'N/A'}
Years in Operation: ${claim.corporateDetails.yearsInOperation || 'N/A'}
` : ''}

${claim.driver ? `
DRIVER INFORMATION
-----------------
Name: ${claim.driver.fullName}
License Number: ${claim.driver.licenseNumber}
License Class: ${claim.driver.licenseClass || 'N/A'}
Issue Date: ${claim.driver.issueDate ? new Date(claim.driver.issueDate).toLocaleDateString() : 'N/A'}
Expiry Date: ${claim.driver.expiryDate ? new Date(claim.driver.expiryDate).toLocaleDateString() : 'N/A'}
` : ''}

${claim.bankDetails ? `
BANK DETAILS
-----------
Bank Name: ${claim.bankDetails.bankName}
Account Name: ${claim.bankDetails.accountName}
Account Number: ${claim.bankDetails.accountNumber}
Branch: ${claim.bankDetails.branchName || 'N/A'}
Swift Code: ${claim.bankDetails.swiftCode || 'N/A'}
` : ''}

Report Generated: ${new Date().toLocaleString()}
Generated by: ClaimFlow AI Staff Portal
  <!DOCTYPE html>
  <html>
  <head>
    <meta charset="UTF-8">
    <title>Motor Accident Insurance Claim Report</title>
    <style>
      body { font-family: Arial, sans-serif; margin: 20px; line-height: 1.4; }
      h1 { color: #2563eb; border-bottom: 3px solid #2563eb; padding-bottom: 10px; }
      h2 { color: #1e40af; border-bottom: 1px solid #e5e7eb; padding-bottom: 5px; margin-top: 25px; }
      .claim-header { background: #f8fafc; padding: 15px; border-radius: 8px; margin-bottom: 20px; }
      .field-row { display: flex; margin-bottom: 8px; }
      .field-label { font-weight: bold; min-width: 150px; color: #374151; }
      .field-value { flex: 1; color: #111827; }
      .section { margin-bottom: 25px; }
      .photo-section { display: flex; flex-wrap: wrap; gap: 15px; margin-top: 15px; }
      .photo-item { border: 1px solid #d1d5db; border-radius: 8px; padding: 10px; max-width: 200px; }
      .photo-item img { max-width: 100%; height: auto; border-radius: 4px; }
      .damage-item { background: #fef3c7; padding: 8px; margin: 5px 0; border-radius: 4px; font-size: 0.9em; }
      .status-badge { padding: 4px 12px; border-radius: 15px; font-size: 0.8em; font-weight: bold; }
      .status-submitted { background: #dbeafe; color: #1e40af; }
      .status-approved { background: #d1fae5; color: #065f46; }
      .status-rejected { background: #fee2e2; color: #991b1b; }
      .status-under_review { background: #fef3c7; color: #92400e; }
      table { width: 100%; border-collapse: collapse; margin: 10px 0; }
      th, td { border: 1px solid #d1d5db; padding: 8px; text-align: left; }
      th { background: #f9fafb; font-weight: bold; }
      .ai-summary { background: #eff6ff; padding: 15px; border-radius: 8px; border-left: 4px solid #3b82f6; }
    </style>
  </head>
  <body>
    <h1>Motor Accident Insurance Claim Report</h1>
    
    <div class="claim-header">
      <div class="field-row">
        <span class="field-label">Claim ID:</span>
        <span class="field-value">${claim.id}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Status:</span>
        <span class="field-value">
          <span class="status-badge status-${claim.status}">${claim.status.toUpperCase().replace('_', ' ')}</span>
        </span>
      </div>
      <div class="field-row">
        <span class="field-label">Date Created:</span>
        <span class="field-value">${new Date(claim.createdAt).toLocaleDateString()}</span>
      </div>
      ${claim.submittedAt ? `
      <div class="field-row">
        <span class="field-label">Date Submitted:</span>
        <span class="field-value">${new Date(claim.submittedAt).toLocaleDateString()}</span>
      </div>
      ` : ''}
    </div>

    <div class="section">
      <h2>Policy Information</h2>
      <div class="field-row">
        <span class="field-label">Policy Number:</span>
        <span class="field-value">${claim.policyNumber || 'N/A'}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Branch Name:</span>
        <span class="field-value">${claim.branchName || 'N/A'}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Agent Name:</span>
        <span class="field-value">${claim.agentName || 'N/A'}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Last Payment Date:</span>
        <span class="field-value">${claim.lastPaymentDate ? new Date(claim.lastPaymentDate).toLocaleDateString() : 'N/A'}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Insured Type:</span>
        <span class="field-value">${claim.insuredType || 'N/A'}</span>
      </div>
    </div>

    ${claim.individualDetails ? `
    <div class="section">
      <h2>Individual Details</h2>
      <div class="field-row">
        <span class="field-label">Full Name:</span>
        <span class="field-value">${claim.individualDetails.firstName} ${claim.individualDetails.middleName || ''} ${claim.individualDetails.surname}</span>
      </div>
      <div class="field-row">
        <span class="field-label">ID Number:</span>
        <span class="field-value">${claim.individualDetails.idNumber}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Nationality:</span>
        <span class="field-value">${claim.individualDetails.nationality || 'N/A'}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Date of Birth:</span>
        <span class="field-value">${claim.individualDetails.dateOfBirth ? new Date(claim.individualDetails.dateOfBirth).toLocaleDateString() : 'N/A'}</span>
      </div>
      <div class="field-row">
        <span class="field-label">PIN Number:</span>
        <span class="field-value">${claim.individualDetails.pinNumber || 'N/A'}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Occupation:</span>
        <span class="field-value">${claim.individualDetails.occupation || 'N/A'}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Mobile:</span>
        <span class="field-value">${claim.individualDetails.mobile || 'N/A'}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Email:</span>
        <span class="field-value">${claim.individualDetails.email || 'N/A'}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Physical Address:</span>
        <span class="field-value">${claim.individualDetails.physicalAddress || 'N/A'}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Postal Address:</span>
        <span class="field-value">${claim.individualDetails.postalAddress || 'N/A'}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Trade/Business:</span>
        <span class="field-value">${claim.individualDetails.tradeBusiness || 'N/A'}</span>
      </div>
    </div>
    ` : ''}

    ${claim.corporateDetails ? `
    <div class="section">
      <h2>Corporate Details</h2>
      <div class="field-row">
        <span class="field-label">Registered Name:</span>
        <span class="field-value">${claim.corporateDetails.registeredName}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Registration Number:</span>
        <span class="field-value">${claim.corporateDetails.registrationNumber}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Country of Registration:</span>
        <span class="field-value">${claim.corporateDetails.countryOfRegistration || 'N/A'}</span>
      </div>
      <div class="field-row">
        <span class="field-label">PIN Number:</span>
        <span class="field-value">${claim.corporateDetails.pinNumber || 'N/A'}</span>
      </div>
      <div class="field-row">
        <span class="field-label">VAT Registration:</span>
        <span class="field-value">${claim.corporateDetails.vatRegNumber || 'N/A'}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Trade/Business:</span>
        <span class="field-value">${claim.corporateDetails.tradeBusiness || 'N/A'}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Years in Operation:</span>
        <span class="field-value">${claim.corporateDetails.yearsInOperation || 'N/A'}</span>
      </div>
    </div>
    ` : ''}

    <div class="section">
      <h2>Accident Details</h2>
      <div class="field-row">
        <span class="field-label">Date:</span>
        <span class="field-value">${claim.accidentDate ? new Date(claim.accidentDate).toLocaleDateString() : 'N/A'}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Time:</span>
        <span class="field-value">${claim.accidentTime || 'N/A'}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Location:</span>
        <span class="field-value">${claim.accidentLocation || 'N/A'}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Description:</span>
        <span class="field-value">${claim.accidentDescription || 'N/A'}</span>
      </div>
    </div>

    ${claim.vehicle ? `
    <div class="section">
      <h2>Vehicle Information</h2>
      <div class="field-row">
        <span class="field-label">Make:</span>
        <span class="field-value">${claim.vehicle.make}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Model:</span>
        <span class="field-value">${claim.vehicle.model}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Year:</span>
        <span class="field-value">${claim.vehicle.yearOfManufacture || 'N/A'}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Registration:</span>
        <span class="field-value">${claim.vehicle.registrationNumber || 'N/A'}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Owner Name:</span>
        <span class="field-value">${claim.vehicle.ownerName || 'N/A'}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Owner Address:</span>
        <span class="field-value">${claim.vehicle.ownerAddress || 'N/A'}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Vehicle Use:</span>
        <span class="field-value">${claim.vehicle.vehicleUse || 'N/A'}</span>
      </div>
    </div>
    ` : ''}

    <div class="section">
      <h2>Damage Assessment</h2>
      <div class="field-row">
        <span class="field-label">Vehicle Damage:</span>
        <span class="field-value">${claim.vehicleDamageDescription || 'N/A'}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Goods Damaged:</span>
        <span class="field-value">${claim.goodsDamaged ? 'Yes' : 'No'}</span>
      </div>
      ${claim.goodsDamaged ? `
      <div class="field-row">
        <span class="field-label">Goods Description:</span>
        <span class="field-value">${claim.goodsDescription || 'N/A'}</span>
      </div>
      ` : ''}
    </div>

    ${claim.damagedPhotos && claim.damagedPhotos.length > 0 ? `
    <div class="section">
      <h2>Uploaded Photos & AI Analysis</h2>
      <div class="ai-summary">
        <strong>AI Analysis Summary:</strong><br>
        Total Photos: ${claim.damagedPhotos.length}<br>
        Total Detected Damages: ${claim.damagedPhotos.reduce((sum, photo) => sum + (photo.detectedDamages?.length || 0), 0)}
      </div>
      
      <div class="photo-section">
        ${claim.damagedPhotos.map(photo => `
          <div class="photo-item">
            <img src="http://localhost:5000${photo.objectPath}" alt="${photo.angle} view" onerror="this.style.display='none'">
            <div><strong>${photo.angle}</strong> ${photo.isGoodsPhoto ? '(Goods)' : '(Vehicle)'}</div>
            ${photo.detectedDamages && photo.detectedDamages.length > 0 ? `
              <div><strong>Detected Damages:</strong></div>
              ${photo.detectedDamages.map(damage => `
                <div class="damage-item">
                  ${damage.damageType} (${Math.round(parseFloat(damage.confidence) * 100)}% confidence)
                  ${damage.severity ? ` - ${damage.severity}` : ''}
                </div>
              `).join('')}
            ` : '<div><em>No damages detected</em></div>'}
          </div>
        `).join('')}
      </div>
    </div>
    ` : ''}

    ${claim.drivers && claim.drivers.length > 0 ? `
    <div class="section">
      <h2>Driver Information</h2>
      ${claim.drivers.map(driver => `
        <div style="margin-bottom: 20px; border: 1px solid #e5e7eb; padding: 15px; border-radius: 8px;">
          <div class="field-row">
            <span class="field-label">Name:</span>
            <span class="field-value">${driver.name}</span>
          </div>
          <div class="field-row">
            <span class="field-label">License Number:</span>
            <span class="field-value">${driver.licenseNumber}</span>
          </div>
          <div class="field-row">
            <span class="field-label">Occupation:</span>
            <span class="field-value">${driver.occupation || 'N/A'}</span>
          </div>
          <div class="field-row">
            <span class="field-label">Date of Birth:</span>
            <span class="field-value">${driver.dateOfBirth ? new Date(driver.dateOfBirth).toLocaleDateString() : 'N/A'}</span>
          </div>
          <div class="field-row">
            <span class="field-label">Years of Driving:</span>
            <span class="field-value">${driver.yearsOfDriving || 'N/A'}</span>
          </div>
          <div class="field-row">
            <span class="field-label">Previous Accidents:</span>
            <span class="field-value">${driver.previousAccidents ? 'Yes' : 'No'}</span>
          </div>
          ${driver.previousAccidents && driver.previousAccidentsDetails ? `
          <div class="field-row">
            <span class="field-label">Accident Details:</span>
            <span class="field-value">${driver.previousAccidentsDetails}</span>
          </div>
          ` : ''}
        </div>
      `).join('')}
    </div>
    ` : ''}

    ${claim.bankDetails ? `
    <div class="section">
      <h2>Bank Details</h2>
      <div class="field-row">
        <span class="field-label">Bank Name:</span>
        <span class="field-value">${claim.bankDetails.bankName}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Account Name:</span>
        <span class="field-value">${claim.bankDetails.accountName}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Account Number:</span>
        <span class="field-value">${claim.bankDetails.accountNumber}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Branch:</span>
        <span class="field-value">${claim.bankDetails.branch || 'N/A'}</span>
      </div>
      <div class="field-row">
        <span class="field-label">Swift Code:</span>
        <span class="field-value">${claim.bankDetails.swiftCode || 'N/A'}</span>
      </div>
    </div>
    ` : ''}

    <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #e5e7eb; text-align: center; color: #6b7280; font-size: 0.9em;">
      <p>Report Generated: ${new Date().toLocaleString()}</p>
      <p>Generated by: ClaimFlow AI Staff Portal</p>
    </div>
  </body>
  </html>
  `;

  await page.setContent(htmlContent, { waitUntil: 'networkidle0' });
  
  const pdfBuffer = await page.pdf({
    format: 'A4',
    printBackground: true,
    margin: {
      top: '20px',
      right: '20px',
      bottom: '20px',
      left: '20px'
    }
  });

  await browser.close();
  return pdfBuffer;
}